### ISSUE TITLE
Consider resetting columns value on term selection

### ISSUE THREAD

**Issue by jeremyfelt** [happyprime/content-aggregator-block#3]
If a term is selected that creates the possibility of having 5 columns, and then a new term is selected with only 3 items, we may want to consider changing the columns number to be the new maximum.

**Comment by philcable** [comment]
I must have pulled this logic from the core Latest Posts block somewhere along the way - in any case, it's still in place in the latest PR: https://github.com/happyprime/content-aggregator-block/pull/49/files#diff-95f4441a0135499a2345d39765099304b7373aff74ec061b604f064277e7c3bbR571.

**Comment by jeremyfelt** [comment]
This seems to work well now! 👍🏻
